In [2]:
import pandas as pd

# 1. Carregar o arquivo CSV (notando que o delimitador do seu arquivo é ';')
df_estoque = pd.read_csv('estoque_produtos_100_itens.csv', sep=';')

In [3]:


# 2. Definir os padrões de Regex para cada categoria
# O caractere '|' funciona como o operador OU (OR) no regex
padrao_limpeza = r'(sabonete|creme dental|detergente|amaciante|shampoo|desinfetante)'

# Para os alimentos, podemos listar as palavras-chave principais do seu estoque
padrao_alimentos = r'(leite|queijo|suco|sal|óleo|arroz|creme|^[creme dental]|presunto|molho|ovos|café|açúcar|cereal|farinha|achocolatado)'

In [4]:
# 3. Criar o DataFrame de Produtos de Limpeza
# case=False garante que vai pegar tanto "Sabonete" quanto "sabonete"
# o .copy copia o dataframe resultante da operação em um novo objeto
df_limpeza = df_estoque[df_estoque['Descricao'].str.contains(padrao_limpeza, case=False, na=False)].copy()
df_limpeza['Categoria'] = "Limpeza"

# 4. Criar o DataFrame de Alimentos
df_alimentos = df_estoque[df_estoque['Descricao'].str.contains(padrao_alimentos, case=False, na=False)].copy()
df_alimentos['Categoria'] = "Alimentos"

print(df_limpeza)
print(df_alimentos)

# concatenar as tabelas
estoque_categorizado = pd.concat([df_limpeza,df_alimentos], axis=0, ignore_index=True)

display(estoque_categorizado.tail(20))

    Codigo  Estoque  Preco  Vencimento                        Descricao  \
8     1008      455  70.08  2026-11-27   Creme Dental Saboroso Refinado
14    1014      840  76.71  2028-03-21  Creme Dental Qualidade Especial
15    1015      325  18.26  2026-09-27       Creme Dental Vida Especial
21    1021      955  21.92  2026-07-01      Detergente Premium Especial
38    1038      573  87.97  2027-03-20    Sabonete Saboroso Tradicional
40    1040      698  48.16  2027-03-05           Creme Dental Vida Zero
49    1049      412  31.66  2026-09-14       Sabonete Saboroso Integral
57    1057      512  46.45  2028-04-09                Sabonete Top Zero
63    1063      208  26.49  2026-12-20            Sabonete Top Refinado
77    1077      827  89.62  2027-11-28     Sabonete Natural Tradicional
82    1082      905  15.56  2027-12-15       Creme Dental Premium Light
84    1084      890   2.99  2027-11-21      Detergente Premium Refinado
87    1087      347  78.17  2027-04-09        Detergente Saboroso Light
93    1093      707  59.59  2027-09-24        Sabonete Premium Refinado
99    1099      302  70.84  2026-08-29             Detergente Top Light

   Categoria
8    Limpeza
14   Limpeza
15   Limpeza
21   Limpeza
38   Limpeza
40   Limpeza
49   Limpeza
57   Limpeza
63   Limpeza
77   Limpeza
82   Limpeza
84   Limpeza
87   Limpeza
93   Limpeza
99   Limpeza
     Codigo  Estoque  Preco  Vencimento                         Descricao  \
0      1000      414  15.72  2028-03-15                  Leite Vida Light
1      1001      959  37.65  2026-10-31          Queijo Saboroso Especial
2      1002      647  39.81  2027-05-25               Suco Qualidade Zero
3      1003       53  87.23  2027-09-29            Sal Qualidade Especial
4      1004      478  66.29  2027-04-09             Óleo Premium Especial
..      ...      ...    ...         ...                               ...
95     1095      910  73.10  2028-02-02        Farinha Qualidade Especial
96     1096      711  44.28  2027-02-25                    Suco Top Light
98     1098      668  67.52  2028-04-27  Molho de Tomate Vida Tradicional
99     1099      302  70.84  2026-08-29              Detergente Top Light
100    1099      102  60.84  2026-08-29                      Cafe Gourmet

     Categoria
0    Alimentos
1    Alimentos
2    Alimentos
3    Alimentos
4    Alimentos
..         ...
95   Alimentos
96   Alimentos
98   Alimentos
99   Alimentos
100  Alimentos

[76 rows x 6 columns]

C:\Users\andre\AppData\Local\Temp\ipykernel_27084\2034540797.py:4: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_limpeza = df_estoque[df_estoque['Descricao'].str.contains(padrao_limpeza, case=False, na=False)].copy()
C:\Users\andre\AppData\Local\Temp\ipykernel_27084\2034540797.py:8: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_alimentos = df_estoque[df_estoque['Descricao'].str.contains(padrao_alimentos, case=False, na=False)].copy()

,Codigo,Estoque,Preco,Vencimento,Descricao,Categoria
71,1075,550,52.00,2028-01-31,Leite Qualidade Tradicional,Alimentos
72,1076,634,11.87,2027-05-25,Cereal Saboroso Refinado,Alimentos
73,1078,999,40.96,2026-06-11,Farinha Extra Especial,Alimentos
74,1079,36,9.13,2027-08-08,Queijo Extra Integral,Alimentos
75,1080,681,60.79,2028-04-27,Achocolatado Premium Zero,Alimentos
76,1081,609,20.87,2028-04-22,Sal Qualidade Tradicional,Alimentos
77,1082,905,15.56,2027-12-15,Creme Dental Premium Light,Alimentos
78,1083,232,76.34,2028-03-16,Queijo Vida Tradicional,Alimentos
79,1084,890,2.99,2027-11-21,Detergente Premium Refinado,Alimentos
80,1087,347,78.17,2027-04-09,Detergente Saboroso Light,Alimentos
81,1088,762,63.16,2027-10-04,Molho de Tomate Fazenda Especial,Alimentos
82,1089,744,81.27,2026-08-01,Farinha Saboroso Tradicional,Alimentos
83,1090,465,26.91,2026-05-31,Açúcar Fazenda Refinado,Alimentos
84,1091,783,60.86,2026-11-25,Presunto Natural Tradicional,Alimentos
85,1094,881,71.30,2026-12-01,Sal Extra Tradicional,Alimentos
86,1095,910,73.10,2028-02-02,Farinha Qualidade Especial,Alimentos
87,1096,711,44.28,2027-02-25,Suco Top Light,Alimentos
88,1098,668,67.52,2028-04-27,Molho de Tomate Vida Tradicional,Alimentos
89,1099,302,70.84,2026-08-29,Detergente Top Light,Alimentos
90,1099,102,60.84,2026-08-29,Cafe Gourmet,Alimentos

In [8]:
# ordenação de valores por um campo
df_resultado = estoque_categorizado.sort_values('Codigo')
display(df_resultado)


df_resultado= estoque_categorizado.sort_values('Preco')
display(df_resultado)

,Codigo,Estoque,Preco,Vencimento,Descricao,Categoria
15,1000,414,15.72,2028-03-15,Leite Vida Light,Alimentos
16,1001,959,37.65,2026-10-31,Queijo Saboroso Especial,Alimentos
17,1002,647,39.81,2027-05-25,Suco Qualidade Zero,Alimentos
18,1003,53,87.23,2027-09-29,Sal Qualidade Especial,Alimentos
19,1004,478,66.29,2027-04-09,Óleo Premium Especial,Alimentos
...,...,...,...,...,...,...
87,1096,711,44.28,2027-02-25,Suco Top Light,Alimentos
88,1098,668,67.52,2028-04-27,Molho de Tomate Vida Tradicional,Alimentos
14,1099,302,70.84,2026-08-29,Detergente Top Light,Limpeza
89,1099,302,70.84,2026-08-29,Detergente Top Light,Alimentos
90,1099,102,60.84,2026-08-29,Cafe Gourmet,Alimentos

,Codigo,Estoque,Preco,Vencimento,Descricao,Categoria
65,1068,756,2.66,2026-12-21,Macarrão Vida Zero,Alimentos
11,1084,890,2.99,2027-11-21,Detergente Premium Refinado,Limpeza
79,1084,890,2.99,2027-11-21,Detergente Premium Refinado,Alimentos
74,1079,36,9.13,2027-08-08,Queijo Extra Integral,Alimentos
46,1036,740,11.28,2028-04-06,Sal Extra Tradicional,Alimentos
...,...,...,...,...,...,...
63,1066,304,87.49,2028-02-27,Óleo Vida Zero,Alimentos
4,1038,573,87.97,2027-03-20,Sabonete Saboroso Tradicional,Limpeza
49,1042,767,88.13,2027-12-08,Queijo Top Tradicional,Alimentos
20,1005,772,89.21,2026-07-24,Arroz Top Especial,Alimentos
9,1077,827,89.62,2027-11-28,Sabonete Natural Tradicional,Limpeza

In [ ]:
df_resultado= estoque_categorizado.groupby('Categoria')['Estoque'].max()
display(df_resultado)


df_resultado= estoque_categorizado.groupby('Categoria')['Preco'].mean()
display(df_resultado)


# podemos concatenar operações para gerar um resultado especifico
faixa_estoque = estoque_categorizado[(estoque_categorizado['Estoque'] < 300) & (estoque_categorizado['Estoque'] > 50)]
df_resultado= faixa_estoque.groupby('Categoria')['Preco'].count()
display(df_resultado)

Categoria
Alimentos    999
Limpeza      955
Name: Estoque, dtype: int64

Categoria
Alimentos    51.532368
Limpeza      49.631333
Name: Preco, dtype: float64

Categoria
Alimentos    14
Limpeza       1
Name: Preco, dtype: int64